# Generated by Django 3.1.5 on 2021-01-20 04:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210115_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
