# Generated by Django 3.1.5 on 2021-01-12 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bloggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('linkedin_url', models.CharField(max_length=255)),
                ('twitter_url', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='media/blog/%Y/%m/')),
                ('description', models.TextField()),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
