# Generated by Django 3.1.5 on 2021-01-12 12:27

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggers',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
