# Generated by Django 3.1.5 on 2021-01-12 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0002_auto_20210112_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggers',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
