# Generated by Django 3.1.5 on 2021-01-12 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0004_bloggers_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggers',
            name='short_description',
            field=models.TextField(max_length=400),
        ),
    ]
