# Generated by Django 3.1.5 on 2021-01-12 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0005_auto_20210112_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloggers',
            name='Specialtag1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='bloggers',
            name='Specialtag2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
