# Generated by Django 3.1.5 on 2021-01-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloggers', '0006_auto_20210112_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloggers',
            name='short_description',
            field=models.TextField(max_length=110),
        ),
    ]
