# Generated by Django 3.1.5 on 2021-01-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0003_securitytext'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='securitytext',
            name='acknowledgmentstxt',
        ),
    ]
