# Generated by Django 3.1.5 on 2021-01-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_remove_securitytext_acknowledgmentstxt'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndroductionBackend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_intro', models.TextField(blank=True, max_length=600)),
                ('indroduction', models.TextField(blank=True)),
            ],
        ),
    ]
