# Generated by Django 3.1.5 on 2021-01-16 09:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0005_indroductionbackend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indroductionbackend',
            name='indroduction',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
