# Generated by Django 3.1.5 on 2021-01-27 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0010_auto_20210118_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='indroductionbackend',
            name='ctf_link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='indroductionbackend',
            name='main_headline',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
