# Generated by Django 3.1.5 on 2021-01-19 02:49

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=255)),
                ('Author_name', models.CharField(blank=True, max_length=255)),
                ('author_linkedin_url', models.CharField(blank=True, max_length=255)),
                ('author_twitter_url', models.CharField(blank=True, max_length=255)),
                ('Course_photo', models.ImageField(upload_to='media/course/%Y/%m/')),
                ('short_description', models.TextField(blank=True, max_length=400)),
                ('description', ckeditor.fields.RichTextField(blank=True)),
                ('is_featured', models.BooleanField(blank=True, default=False)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
