# Generated by Django 3.1.5 on 2021-01-19 03:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_courses_prerequests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='Prerequests',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10),
        ),
    ]
