# Generated by Django 3.1.5 on 2021-01-19 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20210119_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='price',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
