# Generated by Django 3.1.5 on 2021-01-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20210119_1232'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='price',
        ),
    ]
