# Generated by Django 3.1.5 on 2021-01-19 07:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_remove_courses_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='price',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
