# Generated by Django 3.1.5 on 2021-01-19 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_courses_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='price',
        ),
    ]
