# Generated by Django 3.1.5 on 2021-01-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20210119_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='jsonfile',
            field=models.FileField(blank=True, upload_to='initcrew/satic/course/source/'),
        ),
        migrations.AddField(
            model_name='courses',
            name='video',
            field=models.FileField(blank=True, upload_to='media/course/course_vide/%Y/%m/'),
        ),
    ]
