# Generated by Django 3.1.5 on 2021-01-19 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20210119_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='videothumbnail',
            field=models.ImageField(blank=True, upload_to='media/course/thumbnail/'),
        ),
    ]
