# Generated by Django 3.1.5 on 2021-01-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_courses_videothumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='jsonfile',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='video',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='videothumbnail',
        ),
    ]
