# Generated by Django 3.1.5 on 2021-01-19 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0019_auto_20210119_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='videoindroduction',
            field=models.FileField(blank=True, upload_to='media/course/course_vide/%Y/%m/'),
        ),
    ]
