# Generated by Django 3.1.5 on 2021-01-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20210119_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='videoindroduction',
            field=models.FileField(blank=True, upload_to='media/course_video/%Y/'),
        ),
    ]
