# Generated by Django 3.1.5 on 2021-01-20 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0027_auto_20210119_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='videoindroduction',
            field=models.FileField(blank=True, upload_to='course/cvideo/'),
        ),
    ]
